#define BLUECOLOR UIColorFromRGB(0xC7E4EB)
#define YELLOWCOLOR UIColorFromRGB(0xFAFA90)
#define REDCOLOR UIColorFromRGB(0xFFCCC8)

#define CREMECOLOR UIColorFromRGB(0xBBF2A5)
#define GRASSCOLOR UIColorFromRGB(0x9EE6A2)
#define WHITECOLOR UIColorFromRGB(0x78C299)


#define STACKWIDTH 290
#define STACKHEIGHT 400
#define STACKCORNERRAD 6

#define PAGERPAGEWIDTH 320