#define BLUECOLOR UIColorFromRGB(0xC7E4EB)
#define YELLOWCOLOR UIColorFromRGB(0xFAFA90)
#define REDCOLOR UIColorFromRGB(0xFFCCC8)

#define CREMECOLOR UIColorFromRGB(0xEDEAE3)
#define GRASSCOLOR UIColorFromRGB(0xE4F4E1)
#define WHITECOLOR UIColorFromRGB(0xF0FFBF)


#define STACKWIDTH 290
#define STACKHEIGHT 400
#define STACKCORNERRAD 6

#define PAGERPAGEWIDTH 320