#define BLUECOLOR UIColorFromRGB(0xC7E4EB)
#define YELLOWCOLOR UIColorFromRGB(0xFAFA90)
#define REDCOLOR UIColorFromRGB(0xFFCCC8)

#define CREMECOLOR UIColorFromRGB(0xB4EF54)
#define GRASSCOLOR UIColorFromRGB(0xEF4E64)
#define WHITECOLOR UIColorFromRGB(0xE3EF54)


#define STACKWIDTH 290
#define STACKHEIGHT 400
#define STACKCORNERRAD 2

#define PAGERPAGEWIDTH 320